// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using AMR.Financeiro.Infrastructure.Data;
#nullable disable
namespace AMR.Financeiro.Infrastructure.Migrations
{
    [DbContext(typeof(FinanceiroDbContext))]
    [Migration("20260527000001_FixPlanoContasEFS")]
    partial class FixPlanoContasEFS
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
