// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using AMR.Financeiro.Infrastructure.Data;

#nullable disable

namespace AMR.Financeiro.Infrastructure.Migrations
{
    [DbContext(typeof(FinanceiroDbContext))]
    [Migration("20260529000001_SqliteInit")]
    partial class SqliteInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("AMR.Financeiro.Domain.Entities.ContaPagar", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER")
                    .HasAnnotation("Sqlite:Autoincrement", true);
                b.Property<int>("CdFilial").HasColumnType("INTEGER");
                b.Property<DateTime>("CriadoEm").HasColumnType("TEXT");
                b.Property<DateOnly?>("DataPagamento").HasColumnType("TEXT");
                b.Property<string>("Descricao").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("TEXT");
                b.Property<decimal>("Valor").HasPrecision(18, 2).HasColumnType("REAL");
                b.Property<DateOnly>("Vencimento").HasColumnType("TEXT");
                b.HasKey("Id");
                b.ToTable("ContasPagar");
            });

            modelBuilder.Entity("AMR.Financeiro.Domain.Entities.ContaReceber", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER")
                    .HasAnnotation("Sqlite:Autoincrement", true);
                b.Property<int>("CdFilial").HasColumnType("INTEGER");
                b.Property<DateTime>("CriadoEm").HasColumnType("TEXT");
                b.Property<DateOnly?>("DataRecebimento").HasColumnType("TEXT");
                b.Property<string>("Descricao").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                b.Property<string>("DocumentoOrigem").HasMaxLength(100).HasColumnType("TEXT");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("TEXT");
                b.Property<decimal>("Valor").HasPrecision(18, 2).HasColumnType("REAL");
                b.Property<decimal?>("ValorRecebido").HasPrecision(18, 2).HasColumnType("REAL");
                b.Property<DateOnly>("Vencimento").HasColumnType("TEXT");
                b.HasKey("Id");
                b.ToTable("ContasReceber");
            });

            modelBuilder.Entity("AMR.Financeiro.Domain.Entities.LancamentoFinanceiro", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER")
                    .HasAnnotation("Sqlite:Autoincrement", true);
                b.Property<int>("CdFilial").HasColumnType("INTEGER");
                b.Property<DateTime>("CriadoEm").HasColumnType("TEXT");
                b.Property<DateOnly>("DataLancamento").HasColumnType("TEXT");
                b.Property<int?>("DocumentoOrigemId").HasColumnType("INTEGER");
                b.Property<string>("Historico").IsRequired().HasMaxLength(500).HasColumnType("TEXT");
                b.Property<string>("Origem").IsRequired().HasMaxLength(20).HasColumnType("TEXT");
                b.Property<int>("PlanoContasId").HasColumnType("INTEGER");
                b.Property<string>("Tipo").IsRequired().HasMaxLength(20).HasColumnType("TEXT");
                b.Property<decimal>("Valor").HasPrecision(18, 2).HasColumnType("REAL");
                b.HasKey("Id");
                b.HasIndex("PlanoContasId");
                b.ToTable("Lancamentos");
            });

            modelBuilder.Entity("AMR.Financeiro.Domain.Entities.PlanoContas", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER")
                    .HasAnnotation("Sqlite:Autoincrement", true);
                b.Property<bool>("Ativo").HasColumnType("INTEGER");
                b.Property<int>("CdFilial").HasColumnType("INTEGER");
                b.Property<string>("Codigo").IsRequired().HasMaxLength(20).HasColumnType("TEXT");
                b.Property<DateTime>("CriadoEm").HasColumnType("TEXT");
                b.Property<string>("Descricao").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                b.Property<int?>("PaiId").HasColumnType("INTEGER");
                b.Property<string>("Tipo").IsRequired().HasMaxLength(20).HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("PaiId");
                b.HasIndex("CdFilial", "Codigo").IsUnique();
                b.ToTable("PlanoContas");
            });

            modelBuilder.Entity("AMR.Financeiro.Domain.Entities.Usuario", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER")
                    .HasAnnotation("Sqlite:Autoincrement", true);
                b.Property<DateTime>("CriadoEm").HasColumnType("TEXT");
                b.Property<string>("PasswordHash").IsRequired().HasMaxLength(500).HasColumnType("TEXT");
                b.Property<string>("Role").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
                b.Property<string>("Username").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("Username").IsUnique();
                b.ToTable("Usuarios");
            });

            modelBuilder.Entity("AMR.Financeiro.Domain.Entities.LancamentoFinanceiro", b =>
            {
                b.HasOne("AMR.Financeiro.Domain.Entities.PlanoContas", "PlanoContas")
                    .WithMany("Lancamentos")
                    .HasForeignKey("PlanoContasId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.Navigation("PlanoContas");
            });

            modelBuilder.Entity("AMR.Financeiro.Domain.Entities.PlanoContas", b =>
            {
                b.HasOne("AMR.Financeiro.Domain.Entities.PlanoContas", "Pai")
                    .WithMany("Filhos")
                    .HasForeignKey("PaiId")
                    .OnDelete(DeleteBehavior.Restrict);
                b.Navigation("Pai");
            });

            modelBuilder.Entity("AMR.Financeiro.Domain.Entities.PlanoContas", b =>
            {
                b.Navigation("Filhos");
                b.Navigation("Lancamentos");
            });
#pragma warning restore 612, 618
        }
    }
}
