// <auto-generated />
using System;
using AMR.Financeiro.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AMR.Financeiro.Infrastructure.Migrations
{
    [DbContext(typeof(FinanceiroDbContext))]
    partial class FinanceiroDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("AMR.Financeiro.Domain.Entities.Boleto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Banco")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CdFilial")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoBarras")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("TEXT");

                    b.Property<int>("ContaReceberId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataEmissao")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DataPagamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instrucao1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Instrucao2")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LinhaDigitavel")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("NossoNumero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PdfBase64")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SacadoCpfCnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<string>("SacadoEndereco")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("SacadoNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ValorPago")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Vencimento")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Banco", "NossoNumero")
                        .IsUnique();

                    b.ToTable("boletos", (string)null);
                });

            modelBuilder.Entity("AMR.Financeiro.Domain.Entities.CentroCusto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CdFilial")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Nivel")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PaiId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResponsavelNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PaiId");

                    b.HasIndex("CdFilial", "Codigo")
                        .IsUnique();

                    b.ToTable("centroscusto", (string)null);
                });

            modelBuilder.Entity("AMR.Financeiro.Domain.Entities.ContaBancaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Agencia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Conta")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataSaldoInicial")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SaldoInicial")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoConta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ativa");

                    b.ToTable("contas_bancarias", (string)null);
                });

            modelBuilder.Entity("AMR.Financeiro.Domain.Entities.ContaPagar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CdFilial")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DataPagamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Vencimento")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContasPagar", (string)null);
                });

            modelBuilder.Entity("AMR.Financeiro.Domain.Entities.ContaReceber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CdFilial")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DataRecebimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentoOrigem")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ValorRecebido")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Vencimento")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContasReceber", (string)null);
                });

            modelBuilder.Entity("AMR.Financeiro.Domain.Entities.ExtratoBancario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArquivoOriginal")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("CdFilial")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContaCorrente")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportadoEm")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SaldoFinal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SaldoInicial")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalCreditos")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalDebitos")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CdFilial");

                    b.ToTable("extratosbancarios", (string)null);
                });

            modelBuilder.Entity("AMR.Financeiro.Domain.Entities.LancamentoFinanceiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CdFilial")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CentroCustoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContaBancariaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataLancamento")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DocumentoOrigemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Historico")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanoContasId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CentroCustoId");

                    b.HasIndex("ContaBancariaId");

                    b.HasIndex("PlanoContasId");

                    b.ToTable("Lancamentos", (string)null);
                });

            modelBuilder.Entity("AMR.Financeiro.Domain.Entities.MovimentacaoBancaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoDoc")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConciliadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConciliadoPor")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataLancamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExtratoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LancamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusConciliacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExtratoId", "StatusConciliacao");

                    b.ToTable("movimentacoesbancarias", (string)null);
                });

            modelBuilder.Entity("AMR.Financeiro.Domain.Entities.NotaFiscal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ambiente")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CdFilial")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChaveAcesso")
                        .HasMaxLength(44)
                        .HasColumnType("TEXT");

                    b.Property<string>("CpfCnpjDestinatario")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAutorizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataCancelamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("JustificativaCancelamento")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Modelo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MotivoRejeicao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeDestinatario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("NumeroNF")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProtocoloAutorizacao")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("Serie")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("XmlAssinado")
                        .HasColumnType("TEXT");

                    b.Property<string>("XmlAutorizado")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChaveAcesso")
                        .IsUnique();

                    b.HasIndex("CdFilial", "Modelo", "Serie", "NumeroNF")
                        .IsUnique();

                    b.ToTable("notasfiscais", (string)null);
                });

            modelBuilder.Entity("AMR.Financeiro.Domain.Entities.OrcamentoCC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CentroCustoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContaDescricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Mes")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorOrcado")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorRealizado")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CentroCustoId", "ContaDescricao", "Ano", "Mes")
                        .IsUnique();

                    b.ToTable("orcamentoscc", (string)null);
                });

            modelBuilder.Entity("AMR.Financeiro.Domain.Entities.Parcela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContaBancariaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParcelamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorParcela")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContaBancariaId");

                    b.HasIndex("ParcelamentoId");

                    b.HasIndex("Status", "DataVencimento");

                    b.ToTable("parcelas", (string)null);
                });

            modelBuilder.Entity("AMR.Financeiro.Domain.Entities.Parcelamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroParcelas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoVinculo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("VinculoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("parcelamentos", (string)null);
                });

            modelBuilder.Entity("AMR.Financeiro.Domain.Entities.PlanoContas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CdFilial")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PaiId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PaiId");

                    b.HasIndex("CdFilial", "Codigo")
                        .IsUnique();

                    b.ToTable("PlanoContas", (string)null);
                });

            modelBuilder.Entity("AMR.Financeiro.Domain.Entities.PlanoDeContas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AceitaLancamentos")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CdFilial")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("GrupoDRE")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Natureza")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Nivel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrdemExibicao")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PaiId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PaiId");

                    b.HasIndex("CdFilial", "Codigo")
                        .IsUnique();

                    b.ToTable("planodecontas", (string)null);
                });

            modelBuilder.Entity("AMR.Financeiro.Domain.Entities.RateioRealizado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CentroCustoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Competencia")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PercentualAplicado")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("RegraRateioId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorRateado")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RegraRateioId", "Competencia");

                    b.ToTable("rateiosrealizados", (string)null);
                });

            modelBuilder.Entity("AMR.Financeiro.Domain.Entities.RegraRateio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CdFilial")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContaOrigemDescricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoBase")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("regrasrateio", (string)null);
                });

            modelBuilder.Entity("AMR.Financeiro.Domain.Entities.RegraRateioDestino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CentroCustoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Percentual")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("RegraRateioId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ValorBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CentroCustoId");

                    b.HasIndex("RegraRateioId");

                    b.ToTable("regrasrateiodestinos", (string)null);
                });

            modelBuilder.Entity("AMR.Financeiro.Domain.Entities.RemessaBancaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArquivoCnab")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("CdFilial")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoCnab")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalBoletos")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("remessasbancarias", (string)null);
                });

            modelBuilder.Entity("AMR.Financeiro.Domain.Entities.RetornoBancario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArquivoConteudo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArquivoNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("CdFilial")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ProcessadoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalLiquidados")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalRegistros")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorLiquidado")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("retornosbancarios", (string)null);
                });

            modelBuilder.Entity("AMR.Financeiro.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("AMR.Financeiro.Infrastructure.Repositories.ExtratoHash", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CdFilial")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExtratoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportadoEm")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CdFilial", "Hash")
                        .IsUnique();

                    b.ToTable("extratos_hashes", (string)null);
                });

            modelBuilder.Entity("AMR.Financeiro.Domain.Entities.CentroCusto", b =>
                {
                    b.HasOne("AMR.Financeiro.Domain.Entities.CentroCusto", null)
                        .WithMany()
                        .HasForeignKey("PaiId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AMR.Financeiro.Domain.Entities.LancamentoFinanceiro", b =>
                {
                    b.HasOne("AMR.Financeiro.Domain.Entities.CentroCusto", null)
                        .WithMany()
                        .HasForeignKey("CentroCustoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AMR.Financeiro.Domain.Entities.ContaBancaria", null)
                        .WithMany()
                        .HasForeignKey("ContaBancariaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AMR.Financeiro.Domain.Entities.PlanoContas", "PlanoContas")
                        .WithMany("Lancamentos")
                        .HasForeignKey("PlanoContasId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlanoContas");
                });

            modelBuilder.Entity("AMR.Financeiro.Domain.Entities.MovimentacaoBancaria", b =>
                {
                    b.HasOne("AMR.Financeiro.Domain.Entities.ExtratoBancario", null)
                        .WithMany()
                        .HasForeignKey("ExtratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AMR.Financeiro.Domain.Entities.OrcamentoCC", b =>
                {
                    b.HasOne("AMR.Financeiro.Domain.Entities.CentroCusto", null)
                        .WithMany()
                        .HasForeignKey("CentroCustoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AMR.Financeiro.Domain.Entities.Parcela", b =>
                {
                    b.HasOne("AMR.Financeiro.Domain.Entities.ContaBancaria", null)
                        .WithMany()
                        .HasForeignKey("ContaBancariaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AMR.Financeiro.Domain.Entities.Parcelamento", null)
                        .WithMany("Parcelas")
                        .HasForeignKey("ParcelamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AMR.Financeiro.Domain.Entities.PlanoContas", b =>
                {
                    b.HasOne("AMR.Financeiro.Domain.Entities.PlanoContas", "Pai")
                        .WithMany("Filhos")
                        .HasForeignKey("PaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Pai");
                });

            modelBuilder.Entity("AMR.Financeiro.Domain.Entities.PlanoDeContas", b =>
                {
                    b.HasOne("AMR.Financeiro.Domain.Entities.PlanoDeContas", null)
                        .WithMany()
                        .HasForeignKey("PaiId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AMR.Financeiro.Domain.Entities.RateioRealizado", b =>
                {
                    b.HasOne("AMR.Financeiro.Domain.Entities.RegraRateio", null)
                        .WithMany()
                        .HasForeignKey("RegraRateioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AMR.Financeiro.Domain.Entities.RegraRateioDestino", b =>
                {
                    b.HasOne("AMR.Financeiro.Domain.Entities.CentroCusto", null)
                        .WithMany()
                        .HasForeignKey("CentroCustoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AMR.Financeiro.Domain.Entities.RegraRateio", null)
                        .WithMany("Destinos")
                        .HasForeignKey("RegraRateioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AMR.Financeiro.Domain.Entities.Parcelamento", b =>
                {
                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("AMR.Financeiro.Domain.Entities.PlanoContas", b =>
                {
                    b.Navigation("Filhos");

                    b.Navigation("Lancamentos");
                });

            modelBuilder.Entity("AMR.Financeiro.Domain.Entities.RegraRateio", b =>
                {
                    b.Navigation("Destinos");
                });
#pragma warning restore 612, 618
        }
    }
}
